import spotipy
from spotipy.oauth2 import SpotifyOAuth


# Create an account on https://developer.spotify.com/ and use this code yourself.

class SpotPlaylist:
    def __init__(self):
        self.scope = "playlist-modify-private"
        self.sp = spotipy.Spotify(auth_manager=SpotifyOAuth(client_id="Enter Your Client ID Here",
                                                            client_secret="Enter Your Client Secret Here",
                                                            redirect_uri="http://example.com",
                                                            scope=self.scope))
        self.username = self.sp.current_user()["id"]

    def song_list_creation(self, song_name, artist):
        try:
            song_search = self.sp.search(q=f"{artist} {song_name}", limit=1)
        except IndexError:
            print(f"Sorry, {song_name} does not exist in Spotify, song will be skipped")
        else:
            song_uri = song_search["tracks"]["items"][0]["uri"]
            return song_uri

    def playlist_generation(self, date):
        print("Generating Playlist")
        playlist = self.sp.user_playlist_create(user=self.username, name=f"{date} BillBoard 100",
                                                description="This playlist is autogenerated! All songs may not be on "
                                                            "playlist due to the song not existing on Spotify.",
                                                public=False)
        return playlist["id"]

    def adding_songs(self, playlist_id, tracks):
        self.sp.playlist_add_items(playlist_id=playlist_id, items=[f"{tracks}"])
